[build-system]
requires = ["setuptools","extract_msg","pdfkit"]
build-backend = "setuptools.build_meta"

[project]
name = "msg_py"
version = "0.1.0"
description = ".Msg file functions"
authors = [{ name = "CodingBarber" }]
dependencies = []

[tool.setuptools]
packages = ["msg_py"]
